version: "3.0"

services:
  node: 
    build: .
    command: npm run start
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    # environment: 
    #   - PORT=8080
  postgres:
    build: ./database
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}    
    