version: "3"

services:
  node: 
    build: .
    networks:
      - custom-network
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes: 
      - './src:/usr/app/src'
      - 'logs:/usr/app/logs'
  postgres:
    build: ./database
    networks:
      - custom-network
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'postgres-db:/var/lib/postgresql/data'
    
networks:
  custom-network:
    driver: bridge

volumes:
  postgres-db:
  logs:
